#####################################################
## OCTOPENSTACK: Services Configuration Definition ##
#####################################################

user: octopenstack
docker_url : tcp://192.168.59.103:2375

## Specify Docker repository to build containers with

nocache: False
## Pass to True in order to force rebuild of your  
#  containers without using previous cached builds.

services_config:
    HOST_NAME: your_host_name
    HOST_IP: your_host_ip
    RABBITMQ_HOST: your_host_ip
    MYSQL_DB: your_host_ip
    #For one node installation all the hosts are your IP
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
    RABBITMQ_PASSWORD: password
    GLANCE_DBPASS: password
    ADMIN_TOKEN: password
    KEYSTONE_DBPASS: password
    NOVA_DBPASS: password
    ADMIN_PASS: password

